/**
 * HIPAA Breach Notification Types
 */

export enum BreachType {
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  DATA_EXFILTRATION = 'DATA_EXFILTRATION',
  BRUTE_FORCE_ATTACK = 'BRUTE_FORCE_ATTACK',
  UNUSUAL_LOGIN_PATTERN = 'UNUSUAL_LOGIN_PATTERN',
  MASS_DATA_ACCESS = 'MASS_DATA_ACCESS',
  ACCOUNT_COMPROMISE = 'ACCOUNT_COMPROMISE',
  PHI_EXPOSURE = 'PHI_EXPOSURE',
  SYSTEM_INTRUSION = 'SYSTEM_INTRUSION',
}

export enum BreachSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RemediationStatus {
  DETECTED = 'DETECTED',
  INVESTIGATING = 'INVESTIGATING',
  CONTAINED = 'CONTAINED',
  MITIGATED = 'MITIGATED',
  RESOLVED = 'RESOLVED',
}
