[phases.setup]
nixPkgs = ["nodejs_20", "curl", "wget"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.0 --activate",
  "pnpm install --frozen-lockfile --ignore-scripts"
]

[phases.build]
cmds = [
  "pnpm --filter cms build"
]

[start]
cmd = "pnpm --filter cms start"

[variables]
NODE_ENV = "production"
PORT = "3001"
HOSTNAME = "0.0.0.0"
NODE_OPTIONS = "--no-deprecation"
