/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import videoField from '@sklinet/strapi-plugin-video-field/strapi-admin'
import strapiCloud from '@strapi/plugin-cloud/strapi-admin'
import sentry from '@strapi/plugin-sentry/strapi-admin'
import usersPermissions from '@strapi/plugin-users-permissions/strapi-admin'
import { renderAdmin } from '@strapi/strapi/admin'
import strapiAlgolia from 'strapi-plugin-strapi-algolia/strapi-admin'

renderAdmin(document.getElementById('strapi'), {
  plugins: {
    'video-field': videoField,
    'strapi-cloud': strapiCloud,
    sentry: sentry,
    'users-permissions': usersPermissions,
    'strapi-algolia': strapiAlgolia,
  },
})
