[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm payload migrate", "pnpm build"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3001"
