[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.0 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter cms build"
]

[start]
cmd = "pnpm --filter cms start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"
PORT = "3001"
HOSTNAME = "0.0.0.0"
