[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.0 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm build"
]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3001"
HOSTNAME = "0.0.0.0"
